# Generated by Django 4.0.2 on 2022-03-01 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='name_text',
        ),
        migrations.RemoveField(
            model_name='navbar',
            name='name_text',
        ),
        migrations.AddField(
            model_name='car',
            name='make',
            field=models.CharField(default='Make', max_length=20),
        ),
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.CharField(default='Model', max_length=20),
        ),
        migrations.AddField(
            model_name='car',
            name='name',
            field=models.CharField(default='Name', max_length=20),
        ),
        migrations.AddField(
            model_name='car',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='car',
            name='product_image',
            field=models.ImageField(default='car.jpeg', upload_to='cars'),
        ),
        migrations.AddField(
            model_name='navbar',
            name='option_text',
            field=models.CharField(default='Text', max_length=20),
        ),
    ]
