# Generated by Django 4.0.2 on 2022-03-03 17:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_car_name_text_remove_navbar_name_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='product_image',
        ),
        migrations.AddField(
            model_name='car',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 3, 17, 14, 11, 982484, tzinfo=utc), verbose_name='date added'),
        ),
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(default='images/empty-default.jpg', upload_to='home/images'),
        ),
        migrations.AlterField(
            model_name='car',
            name='make',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
