# Generated by Django 4.0.2 on 2022-03-17 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_car_color_car_year_alter_car_date_added'),
        ('home', '0005_remove_car_date_added_remove_car_image_and_more'),
    ]

    operations = [
    ]
