# Generated by Django 3.0 on 2022-03-13 05:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_car_color_car_year_alter_car_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 13, 5, 11, 37, 402129, tzinfo=utc), verbose_name='date added'),
        ),
        migrations.AlterField(
            model_name='car',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='navbar',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
