# Generated by Django 3.0 on 2022-03-13 05:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20220312_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 13, 5, 35, 51, 855049, tzinfo=utc), verbose_name='date added'),
        ),
    ]
