# Generated by Django 4.0.2 on 2022-03-17 00:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_car_image_alter_car_date_added_alter_car_make_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 17, 0, 33, 31, 62091, tzinfo=utc), verbose_name='date added'),
        ),
    ]
