# Generated by Django 4.0.3 on 2022-03-23 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_car_date_added_remove_car_image_and_more'),
        ('home', '0007_auto_20220312_2135'),
    ]

    operations = [
    ]
