# Generated by Django 4.0.3 on 2022-03-23 08:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_merge_20220323_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 23, 8, 10, 25, 550899, tzinfo=utc), verbose_name='date added'),
        ),
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(default='home/images/empty-default.jpg', upload_to='home/images'),
        ),
        migrations.AlterField(
            model_name='car',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='car',
            name='make',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='navbar',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='navbar',
            name='option_text',
            field=models.CharField(default='Text', max_length=20),
        ),
    ]
