# Generated by Django 4.0.2 on 2022-04-13 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_car_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='price',
        ),
        migrations.AddField(
            model_name='car',
            name='image1',
            field=models.ImageField(default='home/images/empty-default.jpg', upload_to='home/images'),
        ),
        migrations.AddField(
            model_name='car',
            name='image2',
            field=models.ImageField(default='home/images/empty-default.jpg', upload_to='home/images'),
        ),
        migrations.AddField(
            model_name='car',
            name='image3',
            field=models.ImageField(default='home/images/empty-default.jpg', upload_to='home/images'),
        ),
        migrations.AddField(
            model_name='car',
            name='image4',
            field=models.ImageField(default='home/images/empty-default.jpg', upload_to='home/images'),
        ),
    ]
