# Generated by Django 4.0.3 on 2022-03-23 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_car_date_added_car_image_alter_car_id_alter_car_make_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='date_added',
        ),
    ]
