# Generated by Django 4.0.3 on 2022-04-29 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_car_image1_car_image2_car_image3_car_image4'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='type',
            field=models.CharField(choices=[('SUV', 'SUV'), ('Sports', 'Sports'), ('Compact', 'Compact'), ('Pick-up', 'Pick-up'), ('Sedan', 'Sedan'), ('Coupe', 'Coupe')], default='type', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(choices=[('Green', 'Green'), ('White', 'White'), ('Black', 'Black'), ('Blue', 'Blue'), ('Red', 'Red'), ('Silver', 'Silver')], default='color', max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='make',
            field=models.CharField(choices=[('FIAT', 'FIAT'), ('Ford', 'Ford'), ('Tesla', 'Tesla'), ('Porche', 'Porche'), ('Hyundai', 'Hyundai'), ('Chevrolet', 'Chevrolet'), ('Kia', 'Kia'), ('GMC', 'GMC'), ('Audi', 'Audi'), ('Polestar', 'Polestar'), ('Jeep', 'Jeep')], default='make', max_length=20),
        ),
    ]
