# Generated by Django 4.0.3 on 2022-03-23 08:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_car_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 23, 8, 52, 56, 630498, tzinfo=utc), verbose_name='date added'),
        ),
    ]
