# Generated by Django 4.0.3 on 2022-03-23 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_car_options_alter_car_date_added'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={},
        ),
    ]
