# Generated by Django 4.0.2 on 2022-05-01 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_profile_favorites_car_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='liked',
        ),
        migrations.AddField(
            model_name='profile',
            name='favorites',
            field=models.ManyToManyField(to='home.Car'),
        ),
    ]
