# Generated by Django 4.0.2 on 2022-05-09 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_car_color_alter_car_make_alter_car_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(choices=[('Red', 'Red'), ('White', 'White'), ('Blue', 'Blue'), ('Black', 'Black'), ('Silver', 'Silver'), ('Green', 'Green')], default='color', max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='make',
            field=models.CharField(choices=[('Ford', 'Ford'), ('Tesla', 'Tesla'), ('Polestar', 'Polestar'), ('Jeep', 'Jeep'), ('Hyundai', 'Hyundai'), ('Audi', 'Audi'), ('FIAT', 'FIAT'), ('GMC', 'GMC'), ('Porche', 'Porche'), ('Kia', 'Kia'), ('Chevrolet', 'Chevrolet')], default='make', max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='type',
            field=models.CharField(choices=[('Compact', 'Compact'), ('Coupe', 'Coupe'), ('Sedan', 'Sedan'), ('Pick-up', 'Pick-up'), ('Sports', 'Sports'), ('SUV', 'SUV')], default='type', max_length=20, null=True),
        ),
    ]
