# Generated by Django 4.0.2 on 2022-05-09 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_car_color_alter_car_make_alter_car_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(choices=[('Black', 'Black'), ('Silver', 'Silver'), ('Green', 'Green'), ('White', 'White'), ('Red', 'Red'), ('Blue', 'Blue')], default='color', max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='make',
            field=models.CharField(choices=[('Audi', 'Audi'), ('Porche', 'Porche'), ('FIAT', 'FIAT'), ('Jeep', 'Jeep'), ('Chevrolet', 'Chevrolet'), ('GMC', 'GMC'), ('Ford', 'Ford'), ('Tesla', 'Tesla'), ('Kia', 'Kia'), ('Polestar', 'Polestar'), ('Hyundai', 'Hyundai')], default='make', max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='type',
            field=models.CharField(choices=[('Sedan', 'Sedan'), ('Compact', 'Compact'), ('Sports', 'Sports'), ('Pick-up', 'Pick-up'), ('SUV', 'SUV'), ('Coupe', 'Coupe')], default='type', max_length=20, null=True),
        ),
    ]
