# Generated by Django 4.0.2 on 2022-05-01 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_remove_car_liked_profile_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='favorites',
        ),
        migrations.AddField(
            model_name='car',
            name='liked',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home.profile'),
        ),
    ]
