# Generated by Django 4.0.2 on 2022-05-01 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_profile_favorites_car_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='liked',
        ),
        migrations.AddField(
            model_name='profile',
            name='liked',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='favorites', to='home.car'),
        ),
    ]
