# Generated by Django 4.0.2 on 2022-05-09 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_car_color_alter_car_make_alter_car_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(choices=[('Black', 'Black'), ('Blue', 'Blue'), ('Green', 'Green'), ('White', 'White'), ('Silver', 'Silver'), ('Red', 'Red')], default='color', max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='make',
            field=models.CharField(choices=[('GMC', 'GMC'), ('Tesla', 'Tesla'), ('Jeep', 'Jeep'), ('Hyundai', 'Hyundai'), ('Chevrolet', 'Chevrolet'), ('Porche', 'Porche'), ('Ford', 'Ford'), ('Audi', 'Audi'), ('Kia', 'Kia'), ('Polestar', 'Polestar'), ('FIAT', 'FIAT')], default='make', max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='type',
            field=models.CharField(choices=[('Sports', 'Sports'), ('Pick-up', 'Pick-up'), ('Coupe', 'Coupe'), ('Compact', 'Compact'), ('Sedan', 'Sedan'), ('SUV', 'SUV')], default='type', max_length=20, null=True),
        ),
    ]
