# Generated by Django 4.0.2 on 2022-05-09 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_car_color_alter_car_make_alter_car_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(choices=[('Black', 'Black'), ('Blue', 'Blue'), ('Green', 'Green'), ('White', 'White'), ('Red', 'Red'), ('Silver', 'Silver')], default='color', max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='make',
            field=models.CharField(choices=[('GMC', 'GMC'), ('Jeep', 'Jeep'), ('Chevrolet', 'Chevrolet'), ('Porche', 'Porche'), ('Ford', 'Ford'), ('Tesla', 'Tesla'), ('FIAT', 'FIAT'), ('Kia', 'Kia'), ('Audi', 'Audi'), ('Hyundai', 'Hyundai'), ('Polestar', 'Polestar')], default='make', max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='type',
            field=models.CharField(choices=[('Coupe', 'Coupe'), ('Pick-up', 'Pick-up'), ('Sedan', 'Sedan'), ('Compact', 'Compact'), ('SUV', 'SUV'), ('Sports', 'Sports')], default='type', max_length=20, null=True),
        ),
    ]
