# Generated by Django 4.0.2 on 2022-05-02 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_remove_car_liked_profile_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='liked',
        ),
    ]
