# Generated by Django 4.0.2 on 2022-05-02 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_remove_profile_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='liked_list',
            field=models.ManyToManyField(to='home.Car'),
        ),
    ]
