# Generated by Django 4.0.2 on 2022-05-02 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_profile_liked_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='liked_list',
        ),
        migrations.AddField(
            model_name='profile',
            name='wishlist',
            field=models.ManyToManyField(to='home.Car'),
        ),
    ]
